### ISSUE TITLE
出现了一些问题，CircleImage和RoundImage都出现了错误，闪退，你可以试下哈

### ISSUE THREAD

**Issue by stay4cold** [CaMnter/EasyRecyclerViewSidebar#1]
I/ActivityManager(28030): screenshot who=ActivityRecord{42070048 u0 com.camnter.easyrecyclerviewsidebar.demo/.MainActivity t104}, w=386, h=687, state=PAUSING, lastbitmap=android.graphics.Bitmap@4314b430, mLastScreenshotActivity=ActivityRecord{42070048 u0 com.camnter.easyrecyclerviewsidebar.demo/.MainActivity t104}, 1=false
E/NewLauncher(28629): DatabaseHandler : DEBUG : handleEventRemoveNewFlagByIntent ids size 0
D/=SOGOU_LOG=(28551): notifyPackageName--notify packageName-- packageName = com.camnter.easyrecyclerviewsidebar.demo
D/dalvikvm(23039): GC_FOR_ALLOC freed 3300K, 26% free 13771K/18584K, paused 13ms, total 14ms, dvmtargetUtilize:0.750000
I/dalvikvm-heap(23039): Grow heap (frag case) to 17.284MB for 1904416-byte allocation
D/dalvikvm(23039): GC_FOR_ALLOC freed 1813K, 33% free 13818K/20444K, paused 11ms, total 11ms, dvmtargetUtilize:0.750000
I/dalvikvm-heap(23039): Grow heap (frag case) to 17.330MB for 1904416-byte allocation
F/libc    (23039): Fatal signal 11 (SIGSEGV) at 0x0000002e (code=1), thread 23039 (iewsidebar.demo)
I/DEBUG   (15079): **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* ***
I/DEBUG   (15079): Build fingerprint: 'smartisan/msm8974sfo/msm8974sfo:4.4.2/SANFRANCISCO:user/dev-keys'
I/DEBUG   (15079): Revision: '0'
I/DEBUG   (15079): pid: 23039, tid: 23039, name: iewsidebar.demo  >>> com.camnter.easyrecyclerviewsidebar.demo <<<
I/DEBUG   (15079): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0000002e
I/DEBUG   (15079):     r0 00000016  r1 757e2010  r2 74d60274  r3 77e9d1f0
I/DEBUG   (15079):     r4 00000016  r5 74d60270  r6 00000001  r7 00000000
I/DEBUG   (15079):     r8 758f3cd4  r9 00000001  sl 40c2cabc  fp bebb8374
I/DEBUG   (15079):     ip 40c2cfe0  sp bebb7f60  lr 40c22c79  pc 404a2e02  cpsr 000f0030

**Comment by CaMnter** [comment]
@wangchenghao 麻烦 提供一下机型和系统版本... 我在虚拟机和6P上测过一遍了没发现这个问题。

**Comment by stay4cold** [comment]
我用的是锤子  版本是4.4.2 smartisan OSv2.5.8

**Comment by CaMnter** [comment]
@wangchenghao 谢谢，刷了一遍测试机，发现就锤子有这个问题。

**Comment by stay4cold** [comment]
@CaMnter 哈哈 这么巧让我给赶上了~

**Comment by CaMnter** [comment]
@wangchenghao 嗯，打出来的log看不到错误，已经在framework层被处理了。

**Comment by stay4cold** [comment]
@CaMnter 看起来像是用到什么导致了底层的内存地址出现了错误 ~

**Comment by CaMnter** [comment]
@wangchenghao 正在寻找解决办法，不行就调JNI了，sad！

**Comment by CaMnter** [comment]
@wangchenghao 再试试，这真的是一个有意思的问题 (｡>﹏<｡)
