### ISSUE TITLE
supportV4和V7的包不能正常依赖

### ISSUE THREAD

**Issue by LandChanning** [CaMnter/EasyRecyclerViewSidebar#3]
clone下来后，supportV4和V7的包不能正常依赖，编译却不报错

**Comment by CaMnter** [comment]
@LandChanning  这个仓库，应该不需要 v4 和 v7，能截图发我看看吗？帮你看看。

**Comment by CaMnter** [comment]
@LandChanning 应该是我写 sample 的时候，有可能用了；或者是 项目生成的时候自动加上了，刚打开项目发现，依赖了，但是应该没用上。

**Comment by LandChanning** [comment]
![image](https://cloud.githubusercontent.com/assets/8448947/16482839/52278fbe-3ee4-11e6-8a34-d9de54e58c3c.png)
我是从这拷贝的SSH连接，然后在studio中直接导入的，然后死活就依赖不到support包。
然后我下了你发布的release版本中的zip，现在可以跑了，不知道是什么原因。。。

不过您响应好快啊，是一直在线吗？

**Comment by CaMnter** [comment]
@LandChanning 有邮箱通知，很快能知道。

**Comment by CaMnter** [comment]
@LandChanning v4 和 v7 的依赖，你可以删掉，应该不会用到。

**Comment by LandChanning** [comment]
![image](https://cloud.githubusercontent.com/assets/8448947/16483305/714ccc0e-3ee6-11e6-8279-e756673ad7ae.png)
这个类里用到ResourcesCompat，是v4包下的

**Comment by CaMnter** [comment]
@LandChanning 嗯，看到了。v4 现在是默认依赖的，项目里目前只 依赖了 v7，应该是新建项目给我默认加上的。那个不能依赖的报错图，能不能发一份，我看看。

**Comment by LandChanning** [comment]
没有报任何错误，只是在代码中找不到support的相关类，在project的External Libraries下面也看不到support的包

**Comment by CaMnter** [comment]
哎，这问题，不太清楚，感觉是环境不同的问题。(｡>﹏<｡) 

![image](https://cloud.githubusercontent.com/assets/10336931/16483893/fa8c4420-3ee8-11e6-84a1-f5bbb1f7daf5.png)

**Comment by LandChanning** [comment]
好像是吧，不纠结这个了，哈哈

**Comment by CaMnter** [comment]
@LandChanning 不过也提醒我，要把我所有项目重整一遍，把不必要的依赖都去掉了。现在 AS 默认帮你集成 v4，然后会自动在新建项目 或者 模块 的时候，在其 gradle 中加入 v7 的依赖 还有 一些测试的依赖。
